language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: lEvNXCCBHm1nIckFK86e1xEqq5rt4nT9GIIH6pz/rJ4/9a1qDW7ulOtHgiYPUnwEVbf55Ng1CLq2638K7vnakOKr7GL/qC5Uz0XJitbgTDDgpRwPEb4NrLcVIsabicQ/5aLvgaHCgOVhsTeA9DmSzWiT4ON3dMFzVeeR3B0xwi1ORv9cg4GGPHhrVeKKc9oLnniN44iqiRzWXW7bqGKEIxEMQr4vXWnM3LK4fEjaopx8rVvM24CoN5REHLYatB1ER6MetVf7RYvKk0pIYyD/q3k9YnUsDJEfWYk+jyYumUM/4umQmmBInILvhiPsGq1pwIjd1rL+lcpI2Y9NeY5C6+9RF0sGDvCdSNtn2+eqDAjuVgq7BPAItnEoDzZ4Gsp7oh/MwvB2J28ykfX0S30kMkmXFSqzV7knsplcldFVlog/g/YZ757/vuzJr0/ohHsZRHePlL/N9daGJ/68usflDqYoIeA8+ymMcHTS5ue2ptt6acb9XCSOgpG84TXAZZG3NsXefzwIyvhqeUMM6suYXFbXGNT29tuxyUZNttnn1o/nKDuuT7zVu5GuHYsLvEDKOut+RN9RmMuEBzh6ClSoJaeypblti/Sg3tTRrD9QzP9CA74zr/QKEQoqgWV7AdQJflZH3G1Tw8D0h4Unjw79xzujWXRCmcepzL+6LM5Zpqw=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
