language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mEm1qpb1fyEtU/hF2nJo4r1c8PbkwS3YhukpNKUFwneH4NNN+94C56nNgSa7F/3RqBXngvpfprg9HnzGdeN4J3rYqkTYG5qoN4U1y4hnJWEJ6AQq20XO2yUe+iOGA+oQZeP1Ej/RFA8C/jKgln1sxfbA3Z9E0onvSjzDhRI3zED06e6NcZeF5+EaMaROYylTFeJ8qhv31A+AbEUvK4WJ4ybZpR0QvKExMs6DIP2CJzIa8hnVSt2/sv9LnErljIz9BU+OT9Ql8v4W0H7FB6XlAnYocsXT3F0+U52P2QfNZ2ubTMz+4Oi9UlQ+gdE3C4GdhqN6PeCj0GFWFZKqxe+Zr+GVBqGoh0OXTfIZ4D4eClkQ7S/14/SvdfzQL15W1tAVL3XdtK2+bsL63jk53doLEsOQx9ANJabxnWH5XZCrLvQNwXOrlvb2GEObXLQ9ldr68+5sDQchX27Xh5ArUyL3bSLZjHgx98+dlB0SKDEV4A5209rh1eMn4nzO+FozyL/vCpVKSERrXgomU2HgILFsHesMgXukw6u7StQIRtparkkFG1mUkTN7X7OY9qH/c1TFBsuPxqytsvrMpc4sfX4hpu5iyrApFL+iemaemIflsXeojcOBUl+iV5QzB2r7QvjYfp1t0ITWqg6ja+TduyCiCm4HXxqRhxuK55xxxvzXKGE=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
