language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: xZegC4f5Xp9ZO2Pz9wK4mVKfcqEkniL1ujZnmCQ7RYOF8jrr6PQYIg/xMLSbnwhVFDYXCF23/YkJD9mkGindkKJfuJdN2lZ0v8jlaNr6IGM9nvE3qYncWG6ePa7PydR+6oTxpqF5SCFTcebkIC6gGWO25zTaEBbv59rNxVvM+It8Wm4GQfEKoWFNS8fzczwgtPXqis7/ewwq8MzwOo6lc0KI4ecskvCzC9YHgieoCNRl1E/oJs8jDJqUWmLrSiB0xfiJTQRolB7K/bTFNMc68yTPRj/8a+tGo1QE+P2EMiMx/wLhyUqmV/o4g41EBpSftLs3Sa1kuWg+KWYrEEQdxJUAjWv9tGNKFGfNci4plMAgLI4o3AFu+PyktNoYfYdNr/n0eR4jHiA/HFiMnLcZV8IFNeHW4SUJ2o1v1zIix9tLYFxO2YB8cFbQJ/JKNZ6h8m19Ucp014Nxl9EuCovxrqdpHRbbIAWjyTQUdnBf9Tuoz5IXuYSiQ/6Ezpz2j0oUOH+s3Aeh+i/33sPQeDlccvikWLio3HBF6J3oHe7RMpbC4bze0O0+lSoHLByzXHP3fWK8CDjN3CB7xYte4I+MG2vn6hwqD054VZfbH/oIfcZn3rj4KMaABVDMfMhL5cjmriq/Jsm00GzzZE6zc+on15Huw0nHbJMR7aUcy3F2hEU=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
