language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DTrjL7nZpWq/j2dMeyGRcBmEU6AEcRJRjN8nmwFS7zBpCi9oxqe0bZkWfJ6nM6ml6303HjLxSjTO48uOJ2wcLsMZwkjp//ZzSptp6ZIdNXfsu5arV8bMHEIGCl2lyQdjPfvIQ6wobS3kdKTLKjaGaYv2isYmRyKzNzZmqL1fBxa5GedPLKVKQVByBi/AUewQSKE0z/5VK1ynlKSQ0mPTjN68kyEkn5NgOmlJ9Ch7bNmmt6mDAiO9fMA18w7ESa2jHtMSpR2jZPgF8n5QS0hXLYcHaSnE9tUVyPRST6Jmbhkmy+dYh6/MnxmBBJopFBVweaGaR2bz5lVahPesU3pMNQmui29hL61AbRt80TbbV10EeaRViTMy2AahOWw7zwTttfJwrA+xy2xzhQSEmTOkRho6SBDB7AqzF4mK9l98SUj7EHVIu1cnlZsQJhabAT6QOznnp9LPHYGFlph7BhwJ0zhRL4WGdcFjaDFlJ8dDmVZz6aE9i4HSwBw/WlgxzAqX4nD0GWm26nogiEH0BoDAqLpc9xd1It+oWpmGlzVGo7RCfSw8p12fHW6JSmJ30EMTkXEhhO3gTf8ekjc3cfEcu+TtUAKGfaRZUR69ZjxUWT+jjXncThiER43MckynTB0/CHYGmCh1+083NkMcZPVtzfGJXnefAJuHFsYsV1eyL7M=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
