language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DM2inU05+foMG52uftWvKeE4RVnAJ639RTEISj7H0HQFBEvCYWeh7dEY+ueKGDhEg0aL9BTiRdKlvfJhVsbmQ1zZw/msS2/dropmVqDh+EYog448nqJTvVz0bX/UKXW3ntOjozXio8p/4y5AKXJ8yzCHW226UIGjlI/njia4Cj7oVPV51N692rKZnymwVZRroXewU7Dzw9FJfi0RA1uACkTqxaCq93vlaW+gZmylv73YNZ01JwneSpLz1VVu5Lx2pQbDrzd0o+hLRC57JtBfQuUdBfhMWU48zjIvAZPU1tIedPHglUymG/rr1INcMXLbCm65eg9F+Dlw070xpgveGI5qxSqtB2fiDMy9D3x4LKItYLrGc7N1M4bcYBep2eG2WrQCCnF1eEEJLQcl5rN4D9eHSU/jG7ggtJ8cAtNbRBu1ghjEgc8o1Y6xw89MMYmPZF1UFDy2y27OsTkBMMEkNWKxkeFdBVl/V/mE4doPiUYVL+DfOYVHv33I2giE9Cnt0auqPyNgXxlRJiJe7tcf/G91UZ8eXbm/mJKPDyB7RBJLRsQHKCtLk0ztysLK1MH6yrpWpKtXf7ugfUhRpvYBxysgkubyrUpACoeL5Mry/b9s3jE0e8KkV87CEwp0uOMkVIX8uMk3lFMbt5tiSl3WFpZMGQ5tTFRyCTVEdrROtTY=
  app: nousfood
  on:
    repo: Quanda/nousfood-client
    branch: master
