language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: oHk8HjW+KxxGDMvy1oXAPb2QsvXV//Trr0XQEM8Bcfyckq92IgkDfcz85cuUj20n0yO0fqNoikEM066cyCHZpwvz8C2cjFt7hqWZk4c+kVq5PxgQro38h0Wid+hcUmXe9O1Yl+q8cqw5Ai4fg1WuC9wvfpgvgvA7Y9DAPObNjRf9NI6aFNyqEM/6gaDhdJ6mqfTP4DahFsJBDS+6Xcnc24wulScaFSYzZj8Tt1BSy5Ax4cMGwA4SEwTSrJATeuswljxHT++uTwg/KX8wvKnlT8Le9K/a8oRyVdxfITQ9rdh/yp4OI8d+rKxhZxkOxl0Ujo1to9CVBhQ0gd++m5Ch1JJ7NpuPOVHAXfWaskBHxd2bSxgq1M1T7AQ5BU3zdF2hzUig7fRA5S9QTS0tmUaxaoQ4Lm/yzb4dwvWSBEpFKhnNhixp0Wrl6dbLr91ZDGiiPYgd1z1hxcjleobyL51oEA7e1EkknT0uomWWGY3OPwxvbioLSNlXheMXs2UsD+nfe/J/n4JXegPbOSBPs601aWoj+KShvnbrvP9lT2QEiA+8ZJcbgQ/zb0W9Dq53YWGnC+4atHEVstk378wlu58q4BWfkNhw3cT481TF32baoEEmdL3GyVjWVF/zT3RrXtNSruUh/UH7koBPFkOeHNL3a6gX/B6H1uStW2VN7ZPt+qI=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
