language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: OG5jRcyaHwerpoiPalIdkHrb23WGw3+T9RsXTIFL5v+BGIXpdX9KOV9/Xj2jVATSfPYqT7w/kmEjgBuIQ8IXDX4dRtALtDo61g1I7+vZNjplqXsJhk5Yhu8ZAMHRq72Oaz7Pqv1FlLKnsP5H7GWDXWAreSLgQD0tTnmdIJ+pJySWGkELLz8fPRk3mUBIM4Uz6nv2pbVXNl3xpHjjZ3Jix1MM92lzchf1UeQBfnSVRgAEmC4XmeYsrC/k8dR6rmj5ci6lweJApzmYLH7wOKT+xfXK70RFbsKVSQKrzlgx7oCVFw4twrw1JbxUFmAy/Y1NVtVgan6/juy3XJdh5OAknUnyVi8nBYEQOQeDJABZvzWiQaLYd1qnG3sWGd25PWLNbNksWuC0bZaw2bix4mTk3dDnb8KMmNvYApncefFLwzooTpo7PhwV+kkGrqp6SZ3da0+iNCxyntu00FbVryy+mTp4+xm5h3P9fNWSPdQ5tMrlgihtV1t90m61gdXTseId0ITCAVr4kx2n9pnqKPuifDX+m+dRZZXgZ3cawsTLGCrbxxVZxtuYZ+9G5llSvHipM1nMSRIVKV8xp9h+zIq4WaK+0ClwAeJRRW+rCfutRcuezJSJeKhV/rQTx7x88HXTb/oTkRhx3egn3AMmUBWJvph0TQqusuLEjmKOHutWRb8=
  app: nousfood
  on:
    repo: Quanda/nousfood-client
    branch: master
