language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: lLTFXUw9Sb2V420Qv6cPXH3LH3+x7kNl00VIoMlleF/9xeeCMjmvxadzt/2Psc8C+WdIqjST9peW0hK2gS2JEgQWG0MURavolvJUO6ShLVezvSjBUDT0dbI1LOfNo8TTOq9+Sb4gVPlRHoC3nkxDgPSusNHIasvzBhqq0UlcWjBINz3bR1MvjQKMZrpTBPZYTXheOhN/HkSwvGNGF8yz3QVFOGC4EQjDTcaEAqDuuNSYkr5iiGz2KAutEIGsuFuM4UaKN2bEnaFi3guDSf2dhf0g9DkZ36+EzJq4xn/GTx7WJrGIF4mWoxipGq5GM3agmWINrUVkhK5XzyS7gSuj8n52n5BtKgdHlGen9/4cpfxK+D7HQ+KlW3ElkpMqcP/IewZtInEjgv3D4nGqhyL7wgvDvqjeyE+o0EEWlih9sHrRSiA1imxJYHMZl70+r4aB0M+DBrAuwcx1Az43+VNfRe5WLBwc+OrBPCUP5WPUK60IaH2AMdhB/oqCXYV2P2tva/lfcy1fQznwU0xiUEgL5kazkLvVL1579KjZOZpHNRgmhwM8Ddt8SnUalJWGHrnR/+urGlNeMxVryZpQ/vyWHEvcvQhRI5c5vvjTNU5CnCZjP/KcvcdUETA/z+8lx5pa5gM48WDGloqZFS58Qszxy39eb8b+N8DFgMFroPZBdq8=
  app: nousfood-client
  on:
    repo: Quanda/nousfood-client
    branch: master
